blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Blank issues
    url: https://github.com/aarnphm/templ/issues/new
    about: To create a blank issue
  - name: Discussions
    url: https://github.com/aarnphm/templ/idiscussions
    about: Please ask general questions here.
